export const texts = [
  "Typing swiftly and precisely is not merely a skill; it's an art that enhances productivity and efficiency in every endeavor.",
  "Exploring the realm of artificial intelligence is like delving into the future, with endless possibilities awaiting discovery.",
  "Learning to code in Python is not just about writing scripts; it's about solving problems and creating innovative solutions.",
  "The impact of social media on modern communication is undeniable, shaping how we interact and share information globally.",
  "Virtual meetings have become a staple in the corporate world, redefining how we conduct business and collaborate across distances.",
  "Investing in cryptocurrencies requires not just financial acumen but also an understanding of emerging digital trends.",
  "The rapid advancements in biotechnology hold promise for groundbreaking treatments and medical interventions.",
  "Automation in manufacturing is transforming industries, increasing efficiency, and reducing human error in production lines.",
  "Renewable energy technologies are not just environmentally friendly; they're crucial for sustainable development.",
  "3D printing is revolutionizing manufacturing, enabling rapid prototyping and customized production on demand.",
  "Online education platforms are making learning accessible to everyone, regardless of geographic or financial constraints.",
  "Smart home devices are enhancing our daily lives, offering convenience and control at the touch of a button.",
  "Digital marketing strategies are evolving rapidly, adapting to the changing dynamics of consumer behavior online.",
  "Cybersecurity is not just a technical issue; it's a critical component of protecting sensitive information in the digital age.",
  "The influence of blockchain extends beyond finance, promising innovations in various sectors including supply chain and healthcare.",
  "The integration of AI in healthcare is enhancing diagnostics and personalized treatment plans, improving patient outcomes.",
  "Virtual reality is expanding beyond gaming, offering immersive experiences in education, training, and therapy.",
  "The rise of e-commerce has transformed retail, providing consumers with unparalleled convenience and choice.",
  "Data science is more than just analyzing numbers; it's about uncovering patterns and insights that drive strategic decisions.",
  "Advancements in telecommunications are connecting the world, making it possible to communicate instantly across vast distances.",
  "Environmental sustainability initiatives are crucial for preserving our planet, requiring a collective effort from all sectors of society.",
];
